### ISSUE TITLE
"https://ci.nodejs.org/"Access Denied

### ISSUE THREAD

**Issue by shipujin** [nodejs/jenkins-alerts#1262]
Hi,
Access "https://ci.nodejs.org/" WEB display:

```
Access Denied
shipujin is missing the Overall/Read permission
```

Best regards

**Comment by UlisesGascon** [comment]
Thanks for reporting @shipujin! This repo is more focused on jenkins-alerts generated automatic, so it is better to open access related issues in the [build repo](https://github.com/nodejs/build) for better visibility.

Currently the CI is under a embargo situation (see: https://github.com/nodejs/build/issues/3622) due a security release planned soon. This means that you can't access to it, until the embargo is completed. For more details, [see](https://github.com/nodejs/build/blob/main/doc/jenkins-guide.md#before-the-release)

Please re-open this issue if you have the same error when the embargo is finished
